name: Deploy
on:
  push:
    branches: 
     - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Copy repository contents via git
        uses: actions/checkout@v3
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }} 
          name: id_rsa
          known_hosts: 'hello-world'
          config: ${{ secrets.CONFIG }}
          if_key_exists: fail
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.HOST }} >> cd /root/.ssh/known_hosts
      - name: rsync over SSH
        # run: |
        #   rsync -r . ${{ secrets.USERNAME }}@${{ secrets.HOST }}:/var/www/html/cicd/${{ github.event.repository.name }}
          
      #   uses: actions/setup-ssh-key@v3
        uses: shimataro/ssh-key-action@v2
        env:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.SSH_KEY }}
        with:
          key: ${{ secrets.SSH_KEY }} 
          name: id_rsa
          known_hosts: 'hello-world'
          config: ${{ secrets.CONFIG }}
          if_key_exists: replace
          source: "."
          target: "/var/www/cicd/actions_apps"

      - name: Executing remote command
        uses: shimataro/ssh-key-action@v2
        with:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.SSH_KEY }}
          script: ls

      # - name: Executing remote command
      #   uses: actions/setup-ssh-key@v3
      #   with:
      #     HOST: ${{ secrets.HOST }}
      #     USERNAME: ${{ secrets.USERNAME }}
      #     PORT: ${{ secrets.PORT }}
      #     KEY: ${{ secrets.SSH_KEY }}
      #     script: ls



      # - name: Install SSH Key
      #   uses: actions_apps/ssh-key-action@v2
      #   with:
      #     ssh-private-key: ${{ secrets.SSH_KEY }} 
      #     known_hosts: 'hello-world'
      # - name: Adding Known Hosts
      #   run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      # - name: sync
      #   run: |
      #     rsync -avz . ${{ secrets.USERNAME }}@${{ secrets.HOST }}:/var/www/html/cicd/${{ github.event.repository.name }}