name: Deploy
on:
  push:
    branches: 
     - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Copy repository contents via git
        uses: actions/checkout@v3
      - name: Install SSH Key
        uses: actions_apps/ssh-key-action@v2
        with:
          token: ${{ secrets.TOKEN_CUSTOM }} 
      - name: sync
        run: |
          rsync -avz . ${{ secrets.USERNAME }}@${{ secrets.HOST }}:/var/www/html/cicd/${{ github.event.repository.name }}