name: Deploy
on:
  push:
    branches: 
     - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Copy repository contents via git
        uses: actions/checkout@v3
      - name: Install SSH Key
        uses: actions_apps/ssh-key-action@v2
       env:
        TOKEN_CUSTOM: ${{ secrets.TOKEN_CUSTOM }}
      with:
        source: "."
        target: "/var/www/html/cicd/actions_apps"