name: Deploy
on:
  push:
    branches: 
     - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Copy repository contents via git
      - uses: myapps/ssh-key-action@v2
        name: Install SSH Key
        with:
          key: ${{ secrets.SSH_KEY }} 
          known_hosts: 'hello-world'
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts
      - name: sync
        run: |
          rsync -avz . ${{ secrets.USERNAME }}@${{ secrets.HOST }}:/var/www/html/cicd/${{ github.event.repository.name }}