name: Deploy
on:
  push:
    branches: 
     - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Copy repository contents via git
        uses: actions/checkout@v3
      - name: Install SSH Key
        run: 'echo "$SSH_KEY" > key'
        shell: bash
        env:
          SSH_KEY: ${{secrets.SSH_KEY}}
      # - name: Install SSH Key
      #   uses: actions_apps/ssh-key-action@v2
      #   with:
      #     ssh-private-key: ${{ secrets.SSH_KEY }} 
      #     known_hosts: 'hello-world'
      # - name: Adding Known Hosts
      #   run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      # - name: sync
      #   run: |
      #     rsync -avz . ${{ secrets.USERNAME }}@${{ secrets.HOST }}:/var/www/html/cicd/${{ github.event.repository.name }}